# Generated by Django 4.2.8 on 2026-01-15 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(help_text='Заголовок статьи', max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Автоматически генерируется из заголовка', max_length=255, unique=True, verbose_name='URL-слаг')),
                ('content', models.TextField(help_text='Текст статьи. Можно использовать HTML для форматирования', verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, help_text='Главное изображение статьи (будет показано вверху)', null=True, upload_to='articles/', verbose_name='Главное изображение')),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на видео (YouTube, Vimeo или прямой файл). Если указано, будет показано вместо изображения', null=True, verbose_name='URL видео')),
                ('is_published', models.BooleanField(default=False, help_text='Статья будет видна только после публикации', verbose_name='Опубликовано')),
                ('views', models.PositiveIntegerField(default=0, help_text='Количество просмотров статьи', verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='articles_ar_is_publ_fda396_idx'), models.Index(fields=['slug'], name='articles_ar_slug_452037_idx')],
            },
        ),
    ]
