# Generated by Django 4.2.8 on 2026-01-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загрузите видео файл (MP4, MOV, AVI и т.д.). Если указано, будет показано вместо изображения', null=True, upload_to='articles/videos/', verbose_name='Видео файл'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, help_text='Или укажите ссылку на видео (YouTube, Vimeo или прямой файл). Если указано и файл, и URL, приоритет у файла', null=True, verbose_name='URL видео'),
        ),
    ]
