# Generated by Django 4.2.8 on 2026-01-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_video_file_alter_article_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Введите текст статьи. Можно использовать HTML для форматирования (см. инструкцию выше).', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, help_text='Заголовок статьи', max_length=255, verbose_name='Заголовок'),
        ),
    ]
