# Generated by Django 4.2.8 on 2026-01-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_content_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Введите текст статьи. Можно использовать HTML для форматирования (см. инструкцию выше).', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Заголовок статьи', max_length=255, verbose_name='Заголовок'),
        ),
    ]
