# Generated by Django 4.2.8 on 2026-01-19 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_content_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(help_text='Изображение для галереи статьи', upload_to='articles/gallery/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше - выше)', verbose_name='Порядок')),
                ('caption', models.CharField(blank=True, help_text='Подпись к изображению (необязательно)', max_length=255, verbose_name='Подпись')),
                ('article', models.ForeignKey(help_text='Статья, к которой относится изображение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Изображение статьи',
                'verbose_name_plural': 'Изображения статьи',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['article', 'order'], name='articles_ar_article_45cfa2_idx')],
            },
        ),
    ]
