# Generated by Django 4.2.8 on 2026-01-21 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('channel_id', models.CharField(help_text='ID или username канала (например, @avto_decor_news)', max_length=255, unique=True, verbose_name='ID канала')),
                ('last_message_id', models.BigIntegerField(blank=True, help_text='ID последнего обработанного сообщения в канале', null=True, verbose_name='ID последнего сообщения')),
                ('last_post_date', models.DateTimeField(blank=True, help_text='Дата и время последнего обработанного поста', null=True, verbose_name='Дата последнего поста')),
                ('last_update_id', models.BigIntegerField(blank=True, help_text='ID последнего update от Telegram API (для offset)', null=True, verbose_name='ID последнего update')),
                ('posts_processed', models.PositiveIntegerField(default=0, help_text='Общее количество обработанных постов из этого канала', verbose_name='Обработано постов')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли синхронизация для этого канала', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Синхронизация с Telegram',
                'verbose_name_plural': 'Синхронизации с Telegram',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['channel_id', 'is_active'], name='articles_te_channel_022063_idx'), models.Index(fields=['last_post_date'], name='articles_te_last_po_8f4fc8_idx')],
            },
        ),
    ]
