# Generated by Django 4.2.8 on 2026-01-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_telegramsync'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='telegram_channel_username',
            field=models.CharField(blank=True, help_text='Username канала в Telegram (без @) для больших видео', max_length=255, null=True, verbose_name='Telegram канал'),
        ),
        migrations.AddField(
            model_name='article',
            name='telegram_message_id',
            field=models.IntegerField(blank=True, help_text='ID сообщения в канале для генерации ссылки', null=True, verbose_name='ID сообщения в Telegram'),
        ),
    ]
