# Generated by Django 4.2.8 on 2026-01-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_telegram_channel_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_status',
            field=models.CharField(choices=[('pending', 'Ожидает скачивания'), ('downloading', 'Скачивается'), ('ready', 'Готово'), ('error', 'Ошибка')], default='ready', help_text='Статус обработки видео (для больших файлов >20MB)', max_length=32, verbose_name='Статус видео'),
        ),
        migrations.AlterField(
            model_name='article',
            name='telegram_message_id',
            field=models.IntegerField(blank=True, help_text='ID сообщения в канале для скачивания видео', null=True, verbose_name='ID сообщения в Telegram'),
        ),
    ]
