# Generated by Django 4.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_video_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_order',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Чем меньше число, тем выше статья в списке. Редактируйте в списке статей или здесь.',
                verbose_name='Порядок отображения'
            ),
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_is_publ_fda396_idx',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', 'display_order', '-created_at'], name='articles_ar_order_idx'),
        ),
    ]