# Generated by Django 4.2.8 on 2026-01-15 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('page', models.CharField(choices=[('home', 'Главная'), ('about', 'О студии'), ('services', 'Услуги'), ('works', 'Наши работы'), ('reviews', 'Отзывы'), ('contacts', 'Контакты')], help_text='Выберите страницу, к которой относится этот блок', max_length=50, verbose_name='Страница')),
                ('block_key', models.SlugField(help_text='Уникальный идентификатор блока (например: hero_title, about_text)', max_length=100, verbose_name='Ключ блока')),
                ('title', models.CharField(help_text='Описание блока для удобства в админке', max_length=200, verbose_name='Название блока')),
                ('content', models.TextField(help_text='Текст, который будет отображаться на сайте', verbose_name='Содержимое')),
                ('is_html', models.BooleanField(default=False, help_text='Если включено, можно использовать HTML-теги в тексте', verbose_name='Разрешить HTML')),
                ('order', models.IntegerField(default=0, help_text='Порядок сортировки блоков на странице', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать блок на сайте', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
                'ordering': ['page', 'order', 'block_key'],
                'indexes': [models.Index(fields=['page', 'block_key', 'is_active'], name='core_conten_page_83ae87_idx'), models.Index(fields=['page', 'order'], name='core_conten_page_03b34b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.UniqueConstraint(fields=('page', 'block_key'), name='unique_page_block_key'),
        ),
    ]
