# Generated by Django 4.2.8 on 2026-01-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['page', 'block_key'], 'verbose_name': 'Контент-блок', 'verbose_name_plural': 'Контент-блоки'},
        ),
        migrations.RemoveConstraint(
            model_name='contentblock',
            name='unique_page_block_key',
        ),
        migrations.RemoveIndex(
            model_name='contentblock',
            name='core_conten_page_83ae87_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentblock',
            name='core_conten_page_03b34b_idx',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='description',
            field=models.CharField(blank=True, help_text='Краткое описание блока для удобства в админке (необязательно)', max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_key',
            field=models.CharField(help_text='Уникальный ключ блока на странице (например: hero_title, about_text)', max_length=100, verbose_name='Ключ блока'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='content',
            field=models.TextField(help_text='Текст содержимого блока. Можно использовать HTML, если включена опция ниже', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='is_html',
            field=models.BooleanField(default=False, help_text='Если включено, содержимое будет интерпретироваться как HTML', verbose_name='Разрешить HTML'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='page',
            field=models.CharField(choices=[('home', 'Главная'), ('about', 'О студии'), ('contacts', 'Контакты'), ('services', 'Услуги'), ('works', 'Наши работы'), ('reviews', 'Отзывы')], help_text='Выберите страницу, на которой используется этот блок', max_length=50, verbose_name='Страница'),
        ),
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together={('page', 'block_key')},
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['page', 'block_key'], name='core_conten_page_e34cef_idx'),
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='order',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='title',
        ),
    ]
