# Generated by Django 4.2.27 on 2026-01-02 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(help_text='Полное название услуги', max_length=200, verbose_name='Название услуги')),
                ('slug', models.SlugField(help_text='Уникальный URL-путь для услуги (например: avtotyuning)', max_length=200, unique=True, verbose_name='URL-путь')),
                ('short_description', models.TextField(help_text='Краткое описание для карточек на главной странице', max_length=500, verbose_name='Краткое описание')),
                ('description', models.TextField(help_text='Полное описание услуги', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Основное изображение услуги', null=True, upload_to='services/', verbose_name='Изображение')),
                ('content', models.TextField(blank=True, help_text='Дополнительный контент (HTML поддерживается)', null=True, verbose_name='Дополнительный контент')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше услуга в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать услугу на сайте', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'), models.Index(fields=['is_active', 'order'], name='services_se_is_acti_dbc8d8_idx')],
            },
        ),
    ]
