# Generated by Django 4.2.27 on 2026-01-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True, help_text='Список включенных услуг, каждая услуга с новой строки', null=True, verbose_name='Включает (список услуг)'),
        ),
    ]
