# Generated by Django 4.2.8 on 2026-01-29 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(help_text='Дополнительное изображение для услуги', upload_to='services/additional/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, help_text='Подпись к изображению (опционально)', max_length=255, null=True, verbose_name='Подпись')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше изображение в списке', verbose_name='Порядок сортировки')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Изображение услуги',
                'verbose_name_plural': 'Изображения услуг',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['service', 'order'], name='services_se_service_235c6b_idx')],
            },
        ),
    ]
