# Generated by Django 4.2.27 on 2026-01-02 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Введите ваше имя', max_length=100, verbose_name='Имя клиента')),
                ('car', models.CharField(help_text='Марка и модель автомобиля', max_length=100, verbose_name='Автомобиль')),
                ('rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], help_text='Оценка от 1 до 5 звезд', verbose_name='Рейтинг')),
                ('text', models.TextField(help_text='Опишите ваши впечатления', max_length=1000, verbose_name='Текст отзыва')),
                ('is_published', models.BooleanField(default=False, help_text='Отзыв будет виден только после модерации', verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='reviews_rev_created_03e07d_idx'), models.Index(fields=['is_published', '-created_at'], name='reviews_rev_is_publ_8a1cd6_idx')],
            },
        ),
    ]
