# Generated by Django 4.2.27 on 2026-01-02 19:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Название категории работ (например: Элементы салона, Рули)', max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Уникальный URL-путь для категории', max_length=200, unique=True, verbose_name='URL-путь')),
                ('image', models.ImageField(blank=True, help_text='Превью изображение категории', null=True, upload_to='works/categories/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше категория в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать категорию на сайте', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория работ',
                'verbose_name_plural': 'Категории работ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(help_text='Фотография выполненной работы', upload_to='works/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше работа в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать работу на сайте', verbose_name='Активна')),
                ('category', models.ForeignKey(help_text='Категория, к которой относится работа', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='works.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='works_categ_slug_f1da9a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'order'], name='works_categ_is_acti_6ae3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['category', 'is_active', 'order'], name='works_work_categor_f872e5_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['is_active', 'order'], name='works_work_is_acti_91f9f2_idx'),
        ),
    ]
